### ISSUE TITLE
Request to Enable Discussions Tab for Community Suppor

### ISSUE THREAD

**Issue by ashish-kus** [betterbrowser/arcfox#100]
Hello! I wanted to suggest enabling the Discussions tab for this repository to help developers like myself engage more easily with the community. Having a dedicated space for questions, guidance, and general discussions would be incredibly helpful, especially for issues that aren’t strictly bug reports but still need insight or assistance.

For example, I'm currently trying to position a popup at the bottom of the screen (with the URL bar and navigation toolbox also at the bottom) and would love to discuss possible approaches. I’m sure other developers could benefit from a place to ask similar questions and share knowledge.

Could we consider enabling Discussions? Thanks so much!

**Comment by LuanderFarias** [comment]
we have a discord server but ill take a look on the discussions feature for sure :)
