### ISSUE TITLE
Support of Arc "Spaces"

### ISSUE THREAD

**Issue by glennDittmann** [betterbrowser/arcfox#28]
Is there support for the arc typical spaces already? If yes how to create one? 
Because on my two machines the plus button in the bottom right of the sidebar shows `new tab`, but not something like `new space`.

**Comment by LuanderFarias** [comment]
i've been thinking about implementing spaces for a while. but it's a hard task for now... at the moment i'm focusing on make firefox usable with arcfox, once i achieve this i'm gonna to add other features like themes, peek, spaces, librar, etc... also, i never tested arc so i don't know exactly how this functions work...

**Comment by glennDittmann** [comment]
Sure, that makes sense, I can understand ! 
If the repo is open for PR I could alos help implementing. I also have arc on my machine for references.

**Comment by LuanderFarias** [comment]
This is totally open to PR's!!! i don't think about implementing that so soon, but if you want to do it i would really appreciate it :)

**Comment by jcdietrich** [comment]
Something that may help with this is Multi-Account Containers
  * https://addons.mozilla.org/en-CA/firefox/addon/multi-account-containers/

**Comment by LuanderFarias** [comment]
@jcdietrich This is actually helpfull!! tysm.

**Comment by menisadi** [comment]
Look at what [Sidebery](https://addons.mozilla.org/en-US/firefox/addon/sidebery/) or [Conex](https://addons.mozilla.org/en-US/firefox/addon/conex/) are able to do with containers, sounds like the reasonable way to go :)

**Comment by LuanderFarias** [comment]
just here to announce that arcfox is back and i'm gonna develop this function :)

**Comment by ljbred08** [comment]
Please add this! I have a situation that might require me to switch to Firefox (from Zen) and I will be desperately needing this!

**Comment by LuanderFarias** [comment]
> Please add this! I have a situation that might require me to switch to Firefox (from Zen) and I will be desperately needing this!

you came in a really clutch time, i was asking on the betterbrowser server if i should archive arcfox...
