### ISSUE TITLE
Open sidebar when hover left on focus mode

### ISSUE THREAD

**Issue by LuanderFarias** [betterbrowser/arcfox#29]
dextarus#7634 Recently asked on arcfox discord (https://discord.ggC2aGfAgAHk) if it's possible to open sidebar when you hover the left border like arc does, at the moment no, but that's a nice feature and i'm implementing soon :)

**Comment by Danielduel** [comment]
Hi @LuanderFarias this is a great feature idea, can I help with this?

**Comment by LuanderFarias** [comment]
> Hi @LuanderFarias this is a great feature idea, can I help with this?

SURE!!

**Comment by LuanderFarias** [comment]
added to roadmap.
