### ISSUE TITLE
Provide a tutorial on how to revert to default Firefox

### ISSUE THREAD

**Issue by theuser18** [betterbrowser/arcfox#40]
Hello! 

I am excited to try ArcFox, but I am weary to try it in its current state in case I do not like it/of bugs. I would greatly appreciate a tutorial on how to reset Firefox to its settings prior to undergoing to ArcFox treatment.

Thanks!

**Comment by LuanderFarias** [comment]
Nice idea!! gonna do it asap. meanwhile you can basically do the process backwards. just remove userchrome.css and than remove the extension. that's it :)

**Comment by LuanderFarias** [comment]
@wannafedora TYSM!!

**Comment by wannafedor4** [comment]
@LuanderFarias Hi. I was the “ghost” in this issue. I see that my pull request was added to the documentation! Thanks!
