### ISSUE TITLE
Voice calls don't work for telegram group chat in Firefox browser

### ISSUE THREAD

**Issue by Ebad2001** [betterbrowser/arcfox#46]
When ever i try to try to join a call it says that my browser does not support telegram group voice chat.
how to fix it?

**Comment by Ebad2001** [comment]
> When ever i try to try to join a call it says that my browser does not support telegram group voice chat. how to fix it?

![image](https://github.com/betterbrowser/arcfox/assets/96353335/415061e2-9ad7-48c1-a53a-2657a78220b9)

**Comment by LuanderFarias** [comment]
This is common problem with firefox itself!! there's no way to totally solve it and it's not arcfox falt. You can check this github issue to learn more...

https://github.com/Ajaxy/telegram-tt/issues/112
