### ISSUE TITLE
TreeStyleTab

### ISSUE THREAD

**Issue by aaronliu0130** [betterbrowser/arcfox#49]
Would an installed ArcFox be able to integrate https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab ?

**Comment by LuanderFarias** [comment]
yep. you can use treestyletab or sidebery instead of arcfox extension but unfortunally you not gonna be able to minimize and resize firefox while the theme is installed. (you can close with alt+f4)

**Comment by LuanderFarias** [comment]
ok. i added on the roadmap a new thing to be able to close, resize and minimize arcfox without arcfox extension. prolly gonna be a simple css trick to hide the buttons but show they small while hovering like this:
![image](https://github.com/betterbrowser/arcfox/assets/69652684/577dc0a6-ec5f-4592-bdc3-399e7adb6421)
gonna develop it asap.

**Comment by aaronliu0130** [comment]
Wait, by completed do you mean it’s implemented?

**Comment by LuanderFarias** [comment]
nope, arcfox is being recoded (see the readme for more info) and this was included on the roadmap.

**Comment by aaronliu0130** [comment]
AFAIK issues should only be closed if they're finished or rejected, but you're the maintainer after all. Do whatever you need! 🙂

**Comment by aaronliu0130** [comment]
Also, I'm more thinking about adding ArcFox styling to TreeStyleTab stuff

**Comment by LuanderFarias** [comment]
makes sense, well you can do whatever you want with the theme. that's the magic of open-source lol :)
