### ISSUE TITLE
Integrate some extensions

### ISSUE THREAD

**Issue by wannafedor4** [betterbrowser/arcfox#51]
We could integrate or create some extensions like uBlock Origin for boosts, and make our own extensions to change the colors of the browser.

**Comment by LuanderFarias** [comment]
changing css of websites is a thing planned on the roadmap. and now that arcfox is finally back we can do it :)

**Comment by wannafedor4** [comment]
just gonna say-
most websites use ```background: #color ;```, instead of ```background-color: #color ;``` or ```background-image: file.png;```

**Comment by wannafedor4** [comment]
just gonna say-
most websites use ```background: #color ;```, instead of ```background-color: #color ;``` or ```background-image: file.png;```

**Comment by LuanderFarias** [comment]
Fair.
