### ISSUE TITLE
UI broken in LibreWolf

### ISSUE THREAD

**Issue by ChristianSch** [betterbrowser/arcfox#52]
I have a freshly installed LibreWolf and added the plugin as well as the css in the chrome folder. I have a very funky header section though. I'm on macOS Sonoma and LibreWolf 121.0-1

<img width="1251" alt="image" src="https://github.com/betterbrowser/arcfox/assets/6138133/d42c6cf1-a487-4f42-bce6-cd3966482939">

**Comment by LuanderFarias** [comment]
the actual theme is very old and not working on firefox new versions. we are getting back on arcfox development now. so it's gonna be fixed soon

**Comment by LuanderFarias** [comment]
added librewolf support to roadmap :)
