### ISSUE TITLE
Little additions to the project

### ISSUE THREAD

**Issue by t0ster30** [betterbrowser/arcfox#54]
Hi!
I‘ve found some plugins/addons to replicate Arc functions:
- Boosts — [Firemonkey](https://addons.mozilla.org/en-US/firefox/addon/firemonkey/) solves almost everything, except the ui (sadly, it‘s closed-source);
- Easels — [this bookmarklet](https://simondmc.com/drawing-bookmarklet) can be combined with [in-url encoding](https://github.com/alcor/itty-bitty/wiki) for sharing;
- Notes — unfortunately [Notes by Firefox](https://github.com/mozilla/notes) is discontinued, and remaining ones ([Bookmark notes](https://github.com/wincohi/bookmark-notes), [Notefox](https://addons.mozilla.org/en-GB/firefox/addon/websites-notes)) do not have syncing built-in.

**Comment by LuanderFarias** [comment]
NICE!! THANK YOU SOOOOOOOO MUCH. It actually helps a lot

**Comment by LuanderFarias** [comment]
Added this on the roadmap so i'm closing it :)
