### ISSUE TITLE
Issue with setting up extension

### ISSUE THREAD

**Issue by Ramy-Ashraf** [betterbrowser/arcfox#67]
![image](https://github.com/betterbrowser/arcfox/assets/85342902/35125708-228a-46ed-9892-30b3188ee346)

I have a problem setting up the extension. first can't find open folder in about:support. Also when I can't find chrome.zip file in releases I found userChrome.css

**Comment by LuanderFarias** [comment]
it's because the "chrome.zip" still under development. at the moment all you need to do is paste the userchrome.css on the chrome folder. to be fair with you i don't recomend using arcfox now.... as said on the readme we are developing a new version of it and we are almost done.

**Comment by Ramy-Ashraf** [comment]
> it's because the "chrome.zip" still under development. at the moment all you need to do is paste the userchrome.css on the chrome folder. to be fair with you i don't recomend using arcfox now.... as said on the readme we are developing a new version of it and we are almost done. 

Okay thanks
