### ISSUE TITLE
[bug] style error in new tab

### ISSUE THREAD

**Issue by PabloRuizCuevas** [betterbrowser/arcfox#69]
When new tab is used i got the left corner white for some reasons:

![image](https://github.com/betterbrowser/arcfox/assets/48098178/2d138a58-e019-4328-af79-e55572fd813e)

Other than that is a very cool repo, thanks for creating this!

**Comment by LuanderFarias** [comment]
Thanks for liking the repo, we made a new release today with a fixed userchrome.css, pls use it
