### ISSUE TITLE
[Question] Sidebar toggle?

### ISSUE THREAD

**Issue by Aoimina** [betterbrowser/arcfox#72]
I saw in the roadmap that the sidebar toggle is implemented but i can't seem to find the button that make it show up only when i hover my mouse to the left rather then it always being there
![image](https://github.com/betterbrowser/arcfox/assets/128810513/95648e40-9d47-474c-9b7e-5be3c05dc539)

**Comment by LuanderFarias** [comment]
Alt+q opens the sidebar
