### ISSUE TITLE
[question] is it possible to run arcfox on macos using wine & firefox intended for windows

### ISSUE THREAD

**Issue by melikootje** [betterbrowser/arcfox#73]
Hey,

so I was wondering if i can run arcfox on macos as the support for monterey of arc browser has been dropped. I was thinking about using wine to emulate windows and install firefox its windows edition to end up using arcfox on the windows instance of firefox.

is this possible? If not, how long untill macos will be getting supported by arcfox?

**Comment by fervflow** [comment]
I think the only requisite to use arcfox is to have the firefox browser installed, then just install the extension and copy the css theme file in the chrome directory, as stated in the [installation instructions](https://github.com/betterbrowser/arcfox?tab=readme-ov-file#installation)

**Comment by LuanderFarias** [comment]
> I think the only requisite to use arcfox is to have the firefox browser installed, then just install the extension and copy the css theme file in the chrome directory, as stated in the [installation instructions](https://github.com/betterbrowser/arcfox?tab=readme-ov-file#installation)

Exactly :)

You might have some problem finding the directory to the put the userchrome.css but it should work normally
