### ISSUE TITLE
Combining bookmarks and tabs

### ISSUE THREAD

**Issue by tknx** [betterbrowser/arcfox#76]
With Manifest 3, thinking about moving from Arc to Firefox.

But the sidebar just appears to be tabs? Whereas Arc has tabs and bookmarks commingled along with a place to pin specific tabs?

You can see here in my screenshot I have gmail/gcal/raindrops pinned at the top, and then a bunch of categorized folders "above the line" and then the tabs are a mix of what is above the line and below.

![Screenshot 2024-08-05 at 12 01 51](https://github.com/user-attachments/assets/4e2b71cc-6362-4b53-8d8a-2e8d3b57400d)

**Comment by LuanderFarias** [comment]
It's a feature under development as you can see on the roadmap :)

**Comment by LuanderFarias** [comment]
the bookmark feature is officialy here :)
