### ISSUE TITLE
Userchrome not loading

### ISSUE THREAD

**Issue by tknx** [betterbrowser/arcfox#78]
Followed the instructions exactly and restarted Firefox - but the stylesheet doesn't load. Any thoughts as to why?

![Screenshot 2024-08-09 at 17 09 05](https://github.com/user-attachments/assets/a4a9ef44-3427-4685-936d-ca480ca44044)
![Screenshot 2024-08-09 at 17 10 07](https://github.com/user-attachments/assets/2696d340-130b-41c8-84f2-d8393d2c2680)

**Comment by LuanderFarias** [comment]
Firefox is a bit weird with their version stuff, pls check if you created the chrome folder in the right place 🙏

**Comment by LuanderFarias** [comment]
Oh, I see now. The chrome folder you created need to be inside of the version folder. Just move your chrome to that folder on top of it and restart your Firefox.

**Comment by GuiMar10** [comment]
Place the chrome folder in the Profile Folder located at about:support
