### ISSUE TITLE
Userchrome all messed up

### ISSUE THREAD

**Issue by ALE22-0fficial** [betterbrowser/arcfox#80]
Firefox version: 129.0.1 (64 bit), Running natively on m1
Mac Os Version: Sonoma 14.5
Opening with Rosetta: Tried (Not working)

The script is not working properly (appears different from provided screenshots on the main page of the project)

How it appears on my end:

<img width="1552" alt="Screenshot 2024-08-20 alle 00 15 30" src="https://github.com/user-attachments/assets/be6d66d4-b872-4345-92f8-336a0e8d99b5">

**Comment by GuiMar10** [comment]
Please remove sideberry extension from Firefox and install the latest ArcFox extension on releases
