### ISSUE TITLE
Combination of settings to achieve [screenshot mockup]?

### ISSUE THREAD

**Issue by CaptainN** [betterbrowser/arcfox#91]
I'd love to be able to achieve something like this:

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/b1c6258c-732d-4ed6-8faa-89a5696efce5">

Changes:
- Move top bar inside content window
- Have it always show (disable auto-hide)
- Hide the sidebar location

I know it's not exactly like Arc (though it's similar to how Arc looks on Windows), but given current behaviors, this would be pretty solid. If out of scope, please close.

**Comment by GuiMar10** [comment]
It looks amazing honestly

**Comment by CaptainN** [comment]
I got pretty close to that mockup with some CSS - the main differences are colors, and sizing, which could be tweaked further.

![image](https://github.com/user-attachments/assets/6e6d078f-150d-4664-9440-9ac099b66283)

**Comment by CaptainN** [comment]
Firefox has a built in sidebar tab mode (hidden behind a config setting) - but it's kind of ugly (yours is nicer):
![image](https://github.com/user-attachments/assets/0c9468d7-efba-422f-b5e1-ec70bec7fd69)

**Comment by LuanderFarias** [comment]
totally possible with some tweaks on our userChrome.css as you just did :)

if you still need something open another issue :)
