### ISSUE TITLE
Extension not loading in new window

### ISSUE THREAD

**Issue by 8BiToe** [betterbrowser/arcfox#94]
When i try to open a new Firefox window when i already have one, the ArcFox extension does not load on the new window. I can only see the custom theme, but there is no sidebar.

**Comment by LuanderFarias** [comment]
pls try pressing alt + Q

**Comment by 8BiToe** [comment]
That seems to have fixed it, i think it should be turned on by default since it's confusing for people that don't know about it

**Comment by LuanderFarias** [comment]
it is coded to be turned on by default by idk why it's not doing it, gonna take a look on that today if i got any spare time from work
